// Seed data for the development database. See seed-spec.md for the source spec.

import type { ItemType, Collection, Item } from '../lib/mock-data';

export const itemTypes: ItemType[] = [
  {
    id: 'type-snippet',
    name: 'snippet',
    icon: 'FaCode',
    color: '#3b82f6',
    isSystem: true,
    itemCount: 0,
  },
  {
    id: 'type-prompt',
    name: 'prompt',
    icon: 'IoSparklesOutline',
    color: '#8b5cf6',
    isSystem: true,
    itemCount: 0,
  },
  {
    id: 'type-command',
    name: 'command',
    icon: 'FaTerminal',
    color: '#f97316',
    isSystem: true,
    itemCount: 0,
  },
  {
    id: 'type-note',
    name: 'note',
    icon: 'FaRegStickyNote',
    color: '#fde047',
    isSystem: true,
    itemCount: 0,
  },
  {
    id: 'type-file',
    name: 'file',
    icon: 'FaFileAlt',
    color: '#6b7280',
    isSystem: true,
    itemCount: 0,
  },
  {
    id: 'type-image',
    name: 'image',
    icon: 'FaFileImage',
    color: '#ec4899',
    isSystem: true,
    itemCount: 0,
  },
  {
    id: 'type-link',
    name: 'link',
    icon: 'LuLink',
    color: '#10b981',
    isSystem: true,
    itemCount: 0,
  },
];

export const collections: Collection[] = [
  {
    id: 'col-react-patterns',
    name: 'React Patterns',
    description: 'Reusable React patterns and hooks',
    itemCount: 0,
    isFavorite: true,
    createdAt: '2026-01-16',
    updatedAt: '2026-01-20',
  },
  {
    id: 'col-ai-workflows',
    name: 'AI Workflows',
    description: 'AI prompts and workflow automations',
    itemCount: 0,
    isFavorite: true,
    createdAt: '2026-01-19',
    updatedAt: '2026-01-22',
  },
  {
    id: 'col-devops',
    name: 'DevOps',
    description: 'Infrastructure and deployment resources',
    itemCount: 0,
    isFavorite: false,
    createdAt: '2026-01-10',
    updatedAt: '2026-01-13',
  },
  {
    id: 'col-terminal-commands',
    name: 'Terminal Commands',
    description: 'Useful shell commands for everyday development',
    itemCount: 0,
    isFavorite: false,
    createdAt: '2026-01-06',
    updatedAt: '2026-01-09',
  },
  {
    id: 'col-design-resources',
    name: 'Design Resources',
    description: 'UI/UX resources and references',
    itemCount: 0,
    isFavorite: false,
    createdAt: '2026-01-02',
    updatedAt: '2026-01-05',
  },
];

export const items: Item[] = [
  // React Patterns
  {
    id: 'item-use-debounce',
    title: 'useDebounce Hook',
    description: 'Delay updating a value until after a specified timeout',
    contentType: 'text',
    content:
      "import { useEffect, useState } from 'react';\n\nexport function useDebounce<T>(value: T, delay: number): T {\n  const [debouncedValue, setDebouncedValue] = useState(value);\n\n  useEffect(() => {\n    const timer = setTimeout(() => setDebouncedValue(value), delay);\n    return () => clearTimeout(timer);\n  }, [value, delay]);\n\n  return debouncedValue;\n}",
    language: 'typescript',
    typeId: 'type-snippet',
    collectionId: 'col-react-patterns',
    tags: ['react', 'hooks', 'performance'],
    isFavorite: true,
    isPinned: true,
    createdAt: '2026-01-20',
    updatedAt: '2026-01-20',
  },
  {
    id: 'item-compound-component',
    title: 'Compound Component Pattern (Tabs)',
    description:
      'Context-based compound component pattern for building flexible Tabs',
    contentType: 'text',
    content:
      "import { createContext, useContext, useState, type ReactNode } from 'react';\n\ntype TabsContextValue = {\n  activeTab: string;\n  setActiveTab: (id: string) => void;\n};\n\nconst TabsContext = createContext<TabsContextValue | null>(null);\n\nfunction useTabsContext() {\n  const context = useContext(TabsContext);\n  if (!context) throw new Error('Tabs components must be used within <Tabs>');\n  return context;\n}\n\nexport function Tabs({ defaultTab, children }: { defaultTab: string; children: ReactNode }) {\n  const [activeTab, setActiveTab] = useState(defaultTab);\n  return (\n    <TabsContext.Provider value={{ activeTab, setActiveTab }}>\n      {children}\n    </TabsContext.Provider>\n  );\n}\n\nTabs.List = function TabsList({ children }: { children: ReactNode }) {\n  return <div className=\"flex gap-2\">{children}</div>;\n};\n\nTabs.Trigger = function TabsTrigger({ id, children }: { id: string; children: ReactNode }) {\n  const { activeTab, setActiveTab } = useTabsContext();\n  return (\n    <button onClick={() => setActiveTab(id)} data-active={activeTab === id}>\n      {children}\n    </button>\n  );\n};\n\nTabs.Content = function TabsContent({ id, children }: { id: string; children: ReactNode }) {\n  const { activeTab } = useTabsContext();\n  return activeTab === id ? <div>{children}</div> : null;\n};",
    language: 'typescript',
    typeId: 'type-snippet',
    collectionId: 'col-react-patterns',
    tags: ['react', 'context', 'patterns'],
    isFavorite: false,
    isPinned: true,
    createdAt: '2026-01-18',
    updatedAt: '2026-01-18',
  },
  {
    id: 'item-cn-utility',
    title: 'cn() Class Name Utility',
    description: 'Merge Tailwind class names with clsx and tailwind-merge',
    contentType: 'text',
    content:
      "import { clsx, type ClassValue } from 'clsx';\nimport { twMerge } from 'tailwind-merge';\n\nexport function cn(...inputs: ClassValue[]) {\n  return twMerge(clsx(inputs));\n}",
    language: 'typescript',
    typeId: 'type-snippet',
    collectionId: 'col-react-patterns',
    tags: ['react', 'tailwind', 'utils'],
    isFavorite: false,
    isPinned: false,
    createdAt: '2026-01-16',
    updatedAt: '2026-01-16',
  },

  // AI Workflows
  {
    id: 'item-code-review-prompt',
    title: 'Code Review Prompt',
    description: 'Prompt template for thorough AI-assisted code reviews',
    contentType: 'text',
    content:
      'Review the following code for correctness, readability, and security issues. Point out any bugs, suggest improvements, and flag anything that violates best practices. Be specific and reference line numbers where possible.\n\n```\n{code}\n```',
    typeId: 'type-prompt',
    collectionId: 'col-ai-workflows',
    tags: ['ai', 'review', 'prompt'],
    isFavorite: true,
    isPinned: true,
    createdAt: '2026-01-22',
    updatedAt: '2026-01-22',
  },
  {
    id: 'item-doc-generation-prompt',
    title: 'Documentation Generation Prompt',
    description: 'Generate docs with a summary, params, and usage examples',
    contentType: 'text',
    content:
      'Generate clear, concise documentation for the following code. Include a summary of what it does, its parameters and return values, and at least one usage example.\n\n```\n{code}\n```',
    typeId: 'type-prompt',
    collectionId: 'col-ai-workflows',
    tags: ['ai', 'docs', 'prompt'],
    isFavorite: false,
    isPinned: false,
    createdAt: '2026-01-21',
    updatedAt: '2026-01-21',
  },
  {
    id: 'item-refactor-prompt',
    title: 'Refactoring Assistant Prompt',
    description:
      'Prompt for safe, behavior-preserving refactors with explanations',
    contentType: 'text',
    content:
      'Refactor the following code to improve readability and maintainability without changing its behavior. Explain each change you make and why it improves the code.\n\n```\n{code}\n```',
    typeId: 'type-prompt',
    collectionId: 'col-ai-workflows',
    tags: ['ai', 'refactor', 'prompt'],
    isFavorite: false,
    isPinned: false,
    createdAt: '2026-01-19',
    updatedAt: '2026-01-19',
  },

  // DevOps
  {
    id: 'item-dockerfile-nextjs',
    title: 'Production Dockerfile (Next.js)',
    description:
      'Multi-stage Dockerfile for a standalone Next.js production build',
    contentType: 'text',
    content:
      'FROM node:20-alpine AS deps\nWORKDIR /app\nCOPY package.json pnpm-lock.yaml ./\nRUN corepack enable && pnpm install --frozen-lockfile\n\nFROM node:20-alpine AS builder\nWORKDIR /app\nCOPY --from=deps /app/node_modules ./node_modules\nCOPY . .\nRUN corepack enable && pnpm build\n\nFROM node:20-alpine AS runner\nWORKDIR /app\nENV NODE_ENV=production\nCOPY --from=builder /app/public ./public\nCOPY --from=builder /app/.next/standalone ./\nCOPY --from=builder /app/.next/static ./.next/static\nEXPOSE 3000\nCMD ["node", "server.js"]',
    language: 'dockerfile',
    typeId: 'type-snippet',
    collectionId: 'col-devops',
    tags: ['docker', 'ci-cd', 'nextjs'],
    isFavorite: true,
    isPinned: false,
    createdAt: '2026-01-13',
    updatedAt: '2026-01-13',
  },
  {
    id: 'item-vercel-deploy-cmd',
    title: 'Deploy to Vercel (Production)',
    description: 'Deploy the current project to production on Vercel',
    contentType: 'text',
    content: 'vercel deploy --prod',
    language: 'bash',
    typeId: 'type-command',
    collectionId: 'col-devops',
    tags: ['deploy', 'vercel', 'cli'],
    isFavorite: false,
    isPinned: false,
    createdAt: '2026-01-12',
    updatedAt: '2026-01-12',
  },
  {
    id: 'item-docker-docs-link',
    title: 'Docker Documentation',
    description: 'Official Docker documentation and guides',
    contentType: 'text',
    content: 'https://docs.docker.com/',
    typeId: 'type-link',
    collectionId: 'col-devops',
    tags: ['docker', 'docs'],
    isFavorite: false,
    isPinned: false,
    createdAt: '2026-01-11',
    updatedAt: '2026-01-11',
  },
  {
    id: 'item-gh-actions-docs-link',
    title: 'GitHub Actions Documentation',
    description: 'Official GitHub Actions documentation for CI/CD workflows',
    contentType: 'text',
    content: 'https://docs.github.com/en/actions',
    typeId: 'type-link',
    collectionId: 'col-devops',
    tags: ['ci-cd', 'github', 'docs'],
    isFavorite: false,
    isPinned: false,
    createdAt: '2026-01-10',
    updatedAt: '2026-01-10',
  },

  // Terminal Commands
  {
    id: 'item-git-log-graph',
    title: 'List Commit History (Graph)',
    description: 'Visualize commit history as a graph with all branches',
    contentType: 'text',
    content: 'git log --oneline --graph --decorate --all',
    language: 'bash',
    typeId: 'type-command',
    collectionId: 'col-terminal-commands',
    tags: ['git'],
    isFavorite: false,
    isPinned: true,
    createdAt: '2026-01-09',
    updatedAt: '2026-01-09',
  },
  {
    id: 'item-docker-prune',
    title: 'Clean Up Unused Docker Resources',
    description: 'Remove unused containers, networks, images, and volumes',
    contentType: 'text',
    content: 'docker system prune -a --volumes',
    language: 'bash',
    typeId: 'type-command',
    collectionId: 'col-terminal-commands',
    tags: ['docker'],
    isFavorite: false,
    isPinned: false,
    createdAt: '2026-01-08',
    updatedAt: '2026-01-08',
  },
  {
    id: 'item-kill-port',
    title: 'Find and Kill Process on Port',
    description: 'Free up a port by killing the process bound to it',
    contentType: 'text',
    content: 'lsof -ti:3000 | xargs kill -9',
    language: 'bash',
    typeId: 'type-command',
    collectionId: 'col-terminal-commands',
    tags: ['process', 'terminal'],
    isFavorite: true,
    isPinned: false,
    createdAt: '2026-01-07',
    updatedAt: '2026-01-07',
  },
  {
    id: 'item-pnpm-update',
    title: 'Update All Dependencies (pnpm)',
    description: 'Update every dependency to its latest version',
    contentType: 'text',
    content: 'pnpm update --latest',
    language: 'bash',
    typeId: 'type-command',
    collectionId: 'col-terminal-commands',
    tags: ['pnpm', 'dependencies'],
    isFavorite: false,
    isPinned: false,
    createdAt: '2026-01-06',
    updatedAt: '2026-01-06',
  },

  // Design Resources
  {
    id: 'item-tailwind-docs',
    title: 'Tailwind CSS Documentation',
    description: 'Official Tailwind CSS utility class reference and guides',
    contentType: 'text',
    content: 'https://tailwindcss.com/docs',
    typeId: 'type-link',
    collectionId: 'col-design-resources',
    tags: ['css', 'tailwind', 'docs'],
    isFavorite: true,
    isPinned: false,
    createdAt: '2026-01-05',
    updatedAt: '2026-01-05',
  },
  {
    id: 'item-shadcn-ui',
    title: 'shadcn/ui',
    description: 'Re-usable components built with Radix UI and Tailwind CSS',
    contentType: 'text',
    content: 'https://ui.shadcn.com',
    typeId: 'type-link',
    collectionId: 'col-design-resources',
    tags: ['components', 'ui'],
    isFavorite: false,
    isPinned: false,
    createdAt: '2026-01-04',
    updatedAt: '2026-01-04',
  },
  {
    id: 'item-radix-ui',
    title: 'Radix UI Primitives',
    description: 'Unstyled, accessible UI primitives for React',
    contentType: 'text',
    content: 'https://www.radix-ui.com/primitives',
    typeId: 'type-link',
    collectionId: 'col-design-resources',
    tags: ['components', 'accessibility'],
    isFavorite: false,
    isPinned: false,
    createdAt: '2026-01-03',
    updatedAt: '2026-01-03',
  },
  {
    id: 'item-react-icons',
    title: 'React Icons',
    description: 'Popular icon packs as React components',
    contentType: 'text',
    content: 'https://react-icons.github.io/react-icons/',
    typeId: 'type-link',
    collectionId: 'col-design-resources',
    tags: ['icons', 'design'],
    isFavorite: false,
    isPinned: false,
    createdAt: '2026-01-02',
    updatedAt: '2026-01-02',
  },
];
